not_related_pages = [
    'Google Scholar',
    'Adult',
    'Head',
    'Calorie',
    'Plant',
    'Millilitre',
    'Centers_for_Disease_Control_and_Prevention',
    'Centers for Disease Control and Prevention',
    'PubMed',
    'National_Health_Service',
    'Sharp_Corporation',
    'Sharp Corporation',
    'International_Classification_of_Diseases',
    'National_Health_Service',
    'Subway_(restaurant)',
    'Nuclear_magnetic_resonance',
    'COVID-19_pandemic_in_Israel#Green_pass',
    'Meta-analysis',
    'Impact_factor',
    'World_Health_Organization',
    'Health',
    'ICD-10',
    'Virus',
    '2014_West_Africa_Ebola_outbreak',
    '2014 West Africa Ebola outbreak',
    'Emotion',
    'Tablet_(pharmacy)',
    'Organ system',
    'Sick leave',
    'Gene'
    ]